### ISSUE TITLE
Fail on error

### ISSUE THREAD

**Issue by mgrachev** [reviewdog/action-rubocop#10]
GitHub Action should fail if rubocop crashes with an error. For example:
```
Error: unrecognized cop FactoryBot/DynamicAttributeDefinedStatically found in .rubocop_todo.yml
```

**Comment by mgrachev** [comment]
Rubocop exits with the code 2 if it terminates abnormally due to invalid configuration, invalid CLI options, or an internal error.

**Comment by mgrachev** [comment]
Similar issue: https://github.com/reviewdog/reviewdog/issues/596

**Comment by mgrachev** [comment]
@haya14busa How can we handle this exit code properly?

**Comment by haya14busa** [comment]
One option is to use `$PIPESTATUS`.

**Comment by mgrachev** [comment]
Wait for a next release...
