### ISSUE TITLE
undefined method as_replacements'

### ISSUE THREAD

**Issue by gd-gauri** [reviewdog/action-rubocop#111]
I have rubocop version 0.89 and am using the latest `action-rubocop@v2`

**Comment by javierjulio** [comment]
Sorry, there isn't enough to go off here or reproduce. More importantly, that's a very old version of Rubocop which is currently at 1.64.1. Try upgrading to see if that helps. Otherwise, best bet is to produce a reproduction for us to review. Thank you.
