### ISSUE TITLE
HEAD_REF pointing to wrong ref

### ISSUE THREAD

**Issue by lmslopes** [reviewdog/action-rubocop#125]
Hi, in action.yml file I think you are wrongly defining the HEAD_REF,
https://github.com/reviewdog/action-rubocop/blob/5e23bb67d79c93e5eb45bdae6d08b04052afec35/action.yml#L81

It should be pointing to HEAD_sha

`#action.yml
...
    BASE_REF: ${{ github.event.pull_request.base.sha }}
    HEAD_REF: ${{ github.event.pull_request.head.sha }}
`

**Comment by ch-minhvu** [comment]
Not sure anyone raised this but this PR caused the issue https://github.com/reviewdog/action-rubocop/pull/103

**Comment by ch-minhvu** [comment]
@toy hi please help to review this issue

**Comment by toy** [comment]
The question about using `github.sha` and not `github.event.pull_request.head.sha` was already asked in the PR, see my reasoning in the comment https://github.com/reviewdog/action-rubocop/pull/103/files#r1654666250
