### ISSUE TITLE
Migrate from docker to composite run actions

### ISSUE THREAD

**Issue by mgrachev** [reviewdog/action-rubocop#25]
Links:
* https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps
* https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

Inspiration:
* https://github.com/reviewdog/action-golangci-lint/pull/46
* https://github.com/reviewdog/action-tflint/pull/28

**Comment by adnikiforov** [comment]
Gotta take a look at this one 👁️

**Comment by mgrachev** [comment]
I have already migrated [action-reek](https://github.com/reviewdog/action-reek). You can take this as an example.
