### ISSUE TITLE
Use suggestions?

### ISSUE THREAD

**Issue by rewritten** [reviewdog/action-rubocop#28]
I am adding code health checks to some of our repos, and I tried to use this action along with https://github.com/reviewdog/action-suggester. Of course it does not work, the suggester action expects to find a diff, not a linter output.

What would be the steps to support suggestions using this image? I can do the grunt work if I'm pointed in the right direction.

**Comment by mgrachev** [comment]
@haya14busa Can you tell us more about the suggest feature and how can we use it with this action?

**Comment by haya14busa** [comment]
That's great to hear!

You need to support rdformat (https://github.com/reviewdog/reviewdog#code-suggestions) as rubocop output.

Example: eslint https://github.com/reviewdog/action-eslint/tree/master/eslint-formatter-rdjson

**Comment by AlexeyMatskevich** [comment]
I will try to do this!

**Comment by mgrachev** [comment]
> I will try to do this!

Thank you. Assigned you 👍

**Comment by mgrachev** [comment]
@AlexeyMatskevich Do you have any progress?

**Comment by gagalago** [comment]
I suppose that this documentation can help to implement this feature: 
- https://docs.rubocop.org/rubocop/1.18/formatters.html 
- https://www.rubydoc.info/gems/rubocop/RuboCop/Formatter/BaseFormatter

**Comment by ohbarye** [comment]
I'm trying to write a custom Rubocop formatter that generates a JSON result with rdformat.
https://github.com/ohbarye/action-rubocop/blob/e15ee5162645c78e70f480bfcb42fea5b000113d/rdjson_formatter.rb

If I spend some more time I may be able to implement the suggestion feature though, should I leave this issue up to the assignee?

Suggestion example:

![image](https://user-images.githubusercontent.com/1811616/128593682-0cd4a4c9-eb82-4b9b-991a-23465e792f98.png)
