### ISSUE TITLE
Can't seem to be able to run the correct rubocop version

### ISSUE THREAD

**Issue by rpbaltazar** [reviewdog/action-rubocop#41]
I'm maintaining [ros-apartment](https://github.com/rails-on-services/apartment/pull/158) and i'm trying to get review dog to run rubocop on it.
Seems like it's always [picking up the latest version of rubocop](https://github.com/rails-on-services/apartment/runs/2514802368) even if i [specify the version in the action configuration](https://github.com/rails-on-services/apartment/blob/rubocop-results-still-different-from-ci/.github/workflows/reviewdog.yml#L20)

Am i missing something?

**Comment by mgrachev** [comment]
@rpbaltazar Hi 👋 Thank you for your feedback and sorry for the long response.

As I can see in your logs, rubocop v0.93.1 was installed, but after that rubocop extensions were installed which installed the latest version of rubocop: 
```
  Successfully installed parallel-1.20.1
  Successfully installed ast-2.4.2
  Successfully installed parser-3.0.1.1
  Successfully installed rainbow-3.0.0
  Successfully installed regexp_parser-2.1.1
  Successfully installed rubocop-ast-1.5.0
  Successfully installed ruby-progressbar-1.11.0
  Successfully installed unicode-display_width-1.7.0
=> Successfully installed rubocop-0.93.1
  9 gems installed
  Successfully installed concurrent-ruby-1.1.8
  Successfully installed i18n-1.8.10
  Successfully installed tzinfo-2.0.4
  Successfully installed zeitwerk-2.4.2
  Successfully installed activesupport-6.1.3.2
  Successfully installed rack-2.2.3
  Successfully installed rubocop-1.14.0
  Successfully installed rubocop-rails-2.10.1
  8 gems installed
  Successfully installed rubocop-performance-1.11.3
  1 gem installed
  Successfully installed rubocop-rspec-2.3.0
  1 gem installed
  Successfully installed rubocop-i18n-3.0.0
  1 gem installed
  Successfully installed rubocop-rake-0.5.1
  1 gem installed
```

To avoid this please set the version of rubocop extensions or nullify them:

```yaml
with:
  rubocop_extensions: ""
```
