### ISSUE TITLE
Set default token to `github_token` input parameter 

### ISSUE THREAD

**Issue by ybiquitous** [reviewdog/action-rubocop#51]
Hi there,

In this issue, I suggest making the `github_token` input parameter **optional** by setting the default token (`secrets.GITHUB_TOKEN` or `github.token`).
The reason is that people can use this action with less configuration code.

https://github.com/reviewdog/action-rubocop/blob/bc5455ef2cd8f9e77232dc19c79bc0e450df8ed3/action.yml#L5-L7

For example, the change would be like this:

```diff
 github_token: 
   description: 'GITHUB_TOKEN' 
-  required: true
+  default: ${{ github.token }}
```

See also:
- https://github.com/dotnet/actions-create-pull-request/blob/6bb739433928fbc2bdc635d41105e124d0dce021/action.yml#L6
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
- https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

**Comment by mgrachev** [comment]
@ybiquitous Hi 👋 

Sorry for the long answer and thank you for your offer. I like it 🙂

**Comment by ybiquitous** [comment]
@mgrachev Thank you so much! 🎉
