### ISSUE TITLE
Abillity to set versions of used gems

### ISSUE THREAD

**Issue by GieForce** [reviewdog/action-rubocop#6]
Hi, 

I'm currently using this action for rubocop which is actually very nice. 
But last week there was an update for `rubocop-rails` which is automatically installed to the latest version in this action. 
The `rubocop-rails` gem is returning errors which currently causes that every time reviewdog runs the rubocop step fails.
Maybe you can make it possible to set versions of the used gems.

**Comment by mgrachev** [comment]
@GieForce 👋Thank you. Yes, it would be helpful.

**Comment by AlexeyMatskevich** [comment]
Hi i will do it!

**Comment by artem-russkikh** [comment]
Is it possible to configure Dockerfile using inputs? https://github.community/t5/GitHub-Actions/Feature-Request-Build-args-support-in-Docker-container-actions/td-p/37802

**Comment by mgrachev** [comment]
@GieForce Done. Now you can test it.
