### ISSUE TITLE
Possible to suggest linting corrections?

### ISSUE THREAD

**Issue by aharpervc** [reviewdog/action-rubocop#73]
Hi, I see it's possible to have reviewdog leave a comment for linting errors. However, it'd be useful if it suggested the corresponding linting correction as well, so that users could apply the suggestion in one click. Is it possible to set up reviewdog to offer suggested corrections as well?

**Comment by aharpervc** [comment]
> HI, action-rubocop already has the suggestion feature since v2.0.0. Why don't you try it?
> 
> ref #28

Yes, this looks like what I want. It looks like the solution is to combine this repo with https://github.com/reviewdog/action-suggester. Where is the documentation for how to enable that? I looked in the readme and also generally searched this repo and I didn't get any hits, besides this issue and your linked issue.

**Comment by ohbarye** [comment]
You don't have to enable the feature, it automatically works by default.
If your GitHub Action doesn't suggest anything, there would be possibilities below.

- You're using `action-rubocop@v1`
- Your offenses are not correctable by rubocop. As you may know, rubocop can't correct all offenses.

**Comment by aharpervc** [comment]
Okay, thanks, I set it up following https://docs.github.com/en/actions/quickstart & the example config from the readme. So I think this issue can be closed, thanks for the help!

---

As an aside, I found the setup process to be fairly confusing
- no "suggestion" example in the readme
- readme screenshots show other config modes, but not suggestion mode
- [the marketplace listing](https://github.com/marketplace/actions/run-rubocop-with-reviewdog) is really unclear what is the right version to expect: 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/441085/168848790-ccc49465-da4f-43b3-b3e4-2507f064d530.png">
- clicking the "use latest version" button shows this screen which basically gives me no instruction on what to actually do (might be GitHub's problem not yours...):
<img width="500" src="https://user-images.githubusercontent.com/441085/168848996-f7de683b-fead-487d-a5a0-7b5e9785731e.png">

**Comment by ohbarye** [comment]
Oh, I realized that's the reason why some people still start using `action-rubocop@v1`...! Thanks for the info.
Regarding the marketplace issue, I'll continue on https://github.com/reviewdog/action-rubocop/issues/74.
