### ISSUE TITLE
GitHub marketplace shows v1 as the latest

### ISSUE THREAD

**Issue by ohbarye** [reviewdog/action-rubocop#74]
Derived from https://github.com/reviewdog/action-rubocop/issues/73#issuecomment-1129012497

## Problem

The [marketplace page](https://github.com/marketplace/actions/run-rubocop-with-reviewdog) still shows **v1** as the latest action-rubocop version in spite of v2 being the latest. Unfortunately, some users start using this GitHub Action's v1 due to that.

<img width="724" alt="168848790-ccc49465-da4f-43b3-b3e4-2507f064d530" src="https://user-images.githubusercontent.com/1811616/168853589-830673ba-2ac0-400a-9b83-27accfbbdcbc.png">

![168848996-f7de683b-fead-487d-a5a0-7b5e9785731e](https://user-images.githubusercontent.com/1811616/168853599-6e9a8057-f024-4cfa-9d98-f82eb9f0814d.png)

## Solution

Why don't you update the description on the marketplace?

So does anyone have permission to edit the [marketplace page](https://github.com/marketplace/actions/run-rubocop-with-reviewdog)? I apparently don't have it.

**Comment by haya14busa** [comment]
I think @reviewdog/actions-maintainer should have a permission to edit the release to publish action to marketplace. https://github.com/reviewdog/action-rubocop/releases/edit/v2
