### ISSUE TITLE
Replace actions/create-release

### ISSUE THREAD

**Issue by massongit** [reviewdog/action-rubocop#85]
https://github.com/reviewdog/action-rubocop/blob/c3efa9691448e63518f7f6d4b64072eb7c797114/.github/workflows/release.yml#L41

`actions/create-release` used above is unmaintained and uses the deprecated Node.js 12.
Therefore, it should be replaced with other Actions.

[FYI]
* Alternate Actions list: https://github.com/actions/create-release
* Error that Node.js 12 is deprecated: https://github.com/reviewdog/action-rubocop/actions/runs/5197723936

**Comment by shmokmt** [comment]
Resolved with https://github.com/reviewdog/action-rubocop/pull/89
